hollymovies/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
import api.views
from accounts.views import SubmittableLoginView, SubmittablePasswordChangeView, SignUpView, ProfilesListView, \
    ProfileDetailView, ProfileUpdateView, ProfileDeleteView
from viewer.views import *


urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello/', hello),
    path('hello2/<s>/', hello2),  # User data: Regular expression, eg. http://127.0.0.1:8000/hello2/cruel/
    path('hello3/', hello3),      # User data: URL encoding, eg. http://127.0.0.1:8000/hello3/?s=cruel
    path('hello4/', hello4),
    path('hello5/<s0>/', hello5),

    path('', home, name='home'),  # home

    #path('genres/', genres, name='genres'),
    path('genres/', GenresView.as_view(), name='genres'),
    #path('genre/create/', GenreFormView.as_view(), name='genre_create'),
    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),
    path('genre/<pk>/', genre, name='genre'),

    #path('movies/', movies, name='movies'),
    path('movies/', MoviesView.as_view(), name='movies'),
    #path('movies_by_rating/', movies_by_rating, name='movies_by_rating'),
    path('movies_by_rating/', MoviesByRatingView.as_view(), name='movies_by_rating'),
    path('movies_by_popularity/', MoviesByPopularityView.as_view(), name='movies_by_populartiy'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/<pk>/', movie, name='movie'),
    path('creators/', CreatorsView.as_view(), name='creators'),
    path('creator/create/', CreatorCreateView.as_view(), name='creator_create'),
    path('creator/update/<pk>/', CreatorUpdateView.as_view(), name='creator_update'),
    path('creator/delete/<pk>/', CreatorDeleteView.as_view(), name='creator_delete'),
    path('creator/<pk>/', CreatorView.as_view(), name='creator'),

    # authentication
    #path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/login/', SubmittableLoginView.as_view(), name='login'),  # vlastní view pro login
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/password_change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('accounts/', include('django.contrib.auth.urls')),  # defaultní view pro přihlašování/odhlašování/změnu hesla...

    path('accounts/profiles/', ProfilesListView.as_view(), name='profiles'),
    path('accounts/profile/<pk>/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/update/<pk>/', ProfileUpdateView.as_view(), name='profile_update'),
    path('accounts/profile/delete/<pk>/', ProfileDeleteView.as_view(), name='profile_delete'),

    # API
    path('api-auth', include('rest_framework.urls'), namespace='rest_framework'),
    path('api/movies/', api.views.MovieList.as_view()),
    path('api/movie/<pk>/', api.views.MovieDetail.as_view()),
]

viewer/models.py
from datetime import date

from django.db.models import Model, CharField, ForeignKey, DO_NOTHING, IntegerField, DateField, TextField, \
    DateTimeField, ManyToManyField, TextChoices


class Genre(Model):
    name = CharField(max_length=20)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Country(Model):
    name = CharField(max_length=64)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class Sex(TextChoices):
    MAN = 'man'
    WOMAN = 'woman'
    NON_BINARY = 'non-binary'


class Creator(Model):
    name = CharField(max_length=32)
    surname = CharField(max_length=32, blank=True)
    birth_date = DateField(null=True, blank=True)
    death_date = DateField(null=True, blank=True)
    birth_place = CharField(max_length=64, null=True, blank=True)
    country = ForeignKey(Country, null=True, blank=True, on_delete=DO_NOTHING)
    sex = CharField(max_length=10, choices=Sex.choices, null=True, blank=True)
    biography = TextField(null=True, blank=True)

    class Meta:
        ordering = ['surname', 'name', 'birth_date']

    def __str__(self):
        return f"{self.name} {self.surname} ({self.birth_date.year})"

    def print_counts(self):
        result = ""
        if self.directed_movies.count() or self.acting_in_movies.count():
            result = "("
            if self.directed_movies.count():
                result += f"director: {self.directed_movies.count()}"
                if self.acting_in_movies.count():
                    result += ", "
            if self.acting_in_movies.count():
                result += f"actor: {self.acting_in_movies.count()}"
            result += ")"
        return result

    def age(self):
        start_date = self.birth_date
        end_date = date.today()
        if self.death_date:
            end_date = self.death_date
        age = end_date.year - start_date.year
        if end_date.month < start_date.month:
            age -= 1
        if end_date.month == start_date.month and end_date.day < start_date.day:
            age -= 1
        return age


class Movie(Model):
    title = CharField(max_length=64)
    title_cz = CharField(max_length=64, blank=True)
    # genre = ForeignKey(Genre, on_delete=DO_NOTHING)
    genres = ManyToManyField(Genre, blank=True, related_name='movies')
    countries = ManyToManyField(Country, blank=True, related_name='movies')
    directors = ManyToManyField(Creator, blank=True, related_name='directed_movies')
    actors = ManyToManyField(Creator, blank=True, related_name='acting_in_movies')
    rating = IntegerField()
    released = DateField()
    length = IntegerField(null=True, blank=True)
    description = TextField(null=True)
    clicked = IntegerField(default=0)
    created = DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title', 'released']

    def __str__(self):
        return f'{self.title} ({self.released.year})'

viewer/views.py
import re
from concurrent.futures._base import LOGGER
from datetime import date

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.exceptions import ValidationError
from django.forms import Form, CharField, IntegerField, DateField, ModelChoiceField, Textarea, ModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView

from viewer.models import Genre, Movie, Creator


# Create your views here.


# view defined as a function
def hello(request):
    return HttpResponse('Hello, world!')


# User data
# Regular expression
def hello2(request, s):
    return HttpResponse(f'Hello, {s} world!')


# User data
# URL encoding
def hello3(request):
    s = request.GET.get('s', '')
    return HttpResponse(f'Hello, {s} world!')


def hello4(request):
    adjectives = ['nice', 'beautiful', 'cruel', 'blue', 'sunny']
    context = {'adjectives': adjectives}
    return render(
        request,   # předáváme na další stránku request (obsahuje např. data o přihlášeném uživateli)
        template_name='hello.html',  # tato teplate to zobrazí
        context=context   # posíláme data (jako slovník)
    )


@login_required
def hello5(request, s0):
    s1 = request.GET.get('s1', '')
    return render(
        request,
        template_name='hello.html',
        context={'adjectives': [s0, s1, 'beautiful', 'wonderful']}
    )


def home(request):
    return render(request, 'home.html', {'title': 'Welcome to HollyMovies'})


def genres(request):
    result = Genre.objects.all().order_by('name')
    return render(request, 'genres.html', {'title': 'List of genres', 'genres': result})


def movies(request):
    result = Movie.objects.all().order_by('title')
    return render(request, 'movies.html', {'title': 'List of movies', 'movies': result})


def movies_by_rating(request):
    result = Movie.objects.all().order_by('-rating', 'title')
    return render(request,
                  'movies_by_rating.html',
                  {'title': 'List of movies by rating', 'movies': result})


def movies_by_popularity(request):
    result = Movie.objects.all().order_by('-clicked', 'title')
    return render(request,
                  'movies_by_popularity.html',
                  {'title': 'List of movies by popularity', 'movies': result})



# DONE: detailní informace o jednom konkrétním filmu (id zadané v adrese)
# DONE: template
# DONE: view
# DONE: url
# DONE: odkaz z názvu filmu v seznamu filmů (movies)
def movie(request, pk):
    if Movie.objects.filter(id=pk).exists():  # otestujeme, zda film existuje
        result = Movie.objects.get(id=pk)
        result.clicked += 1
        result.save()
        return render(request, 'movie.html', {'title': result.title, 'movie': result})

    # pokud daný film neexistuje, vypíšeme seznam všech filmů
    # TODO: lepší by bylo vypsat chybovou hlášku
    result = Movie.objects.all().order_by('title')
    return render(request,
                  'movies.html',
                  {'title': 'Movies', 'movies': result})


def genre(request, pk):
    if Genre.objects.filter(id=pk).exists():
        genre = Genre.objects.get(id=pk)
        items = genre.movies.all()  #Movie.objects.filter(genre=genre)
        return render(request,
                      "genre.html",
                      {'movies': items, 'genre': genre})

    return genres(request)


""" Class-Based Views """

""" 
# první verze pomocí View - jen se funkce vloží do třídy
class MoviesView(View):
    def get(self, request):
        result = Movie.objects.all().order_by('title')
        return render(request,
                      'movies.html',
                      {'title': 'List of movies', 'movies': result})
"""


"""
# druhá verze pomocí TemplateView - již potřebujeme jen zada jméno tamplaty a data
class MoviesView(TemplateView):
    template_name = 'movies.html'
    extra_context = {'title': 'List of movies',
                     'movies': Movie.objects.all().order_by('title')}
"""


# třetí verze pomocí ListView (zobrazení seznamu) - již definujeme jenom template a model
class MoviesView(ListView):
    template_name = 'movies2.html'
    model = Movie


# druhá verze pomocí TemplateView - již potřebujeme jen zada jméno tamplaty a data
class MoviesByRatingView(TemplateView):
    template_name = 'movies_by_rating.html'
    extra_context = {'title': 'List of movies by rating',
                     'movies': Movie.objects.all().order_by('-rating', 'title')}


class MoviesByPopularityView(TemplateView):
    template_name = 'movies_by_popularity.html'
    extra_context = {'title': 'List of movies by popularity',
                     'movies': Movie.objects.all().order_by('-clicked', 'title')}


class MovieView(View):
    def get(self, request, pk):
        if Movie.objects.filter(id=pk).exists():  # otestujeme, zda film existuje
            result = Movie.objects.get(id=pk)
            return render(request, 'movie.html', {'title': result.title, 'movie': result})

        # pokud daný film neexistuje, vypíšeme seznam všech filmů
        # TODO: lepší by bylo vypsat chybovou hlášku
        result = Movie.objects.all().order_by('title')
        return render(request,
                      'movies.html',
                      {'title': 'Movies', 'movies': result})


"""
class GenresView(View):
    def get(self, request):
        result = Genre.objects.all().order_by('name')
        return render(request,
                      'genres.html',
                      {'title': 'List of genres', 'genres': result})
"""


"""
class GenresView(TemplateView):
    template_name = 'genres.html'
    extra_context = {'title': 'List of genres', 'genres': Genre.objects.all()}
"""


class GenresView(ListView):
    template_name = 'genres2.html'
    model = Genre


class CreatorsView(ListView):
    template_name = 'creators.html'
    model = Creator
    context_object_name = 'creators'


class CreatorView(View):
    def get(self, request, pk):
        if Creator.objects.filter(id=pk).exists():  # otestujeme, zda film existuje
            result = Creator.objects.get(id=pk)
            return render(request, 'creator.html', {'title': result, 'creator': result})

        result = Creator.objects.all()
        return render(request,
                      'creators.html',
                      {'title': 'Creators', 'creators': result})


""" Forms """

""" Validators """


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized.')


class PastMonthField(DateField):

    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


class MovieForm(Form):
    title = CharField(max_length=64)
    genre = ModelChoiceField(queryset=Genre.objects)
    rating = IntegerField(min_value=1, max_value=10)
    released = DateField()
    description = CharField(widget=Textarea, required=False)

    def clean_title(self):
        initial_data = super().clean()  # původní data ve formuláři od uživatele
        initial = initial_data['title']  # původní title od uživatele
        return initial.strip()  # odtraníme prázdné znaky na začátku a konci textu

    def clean_description(self):
        # Force each sentence of the description to be capitalized.
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        return '. '.join(sentence.capitalize() for sentence in sentences)

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'Commedy' and result['rating'] > 5:
            self.add_error('genre', '')
            self.add_error('rating', '')
            raise ValidationError(
                "Commedies aren't so good to be rated over 5."
            )
        return result


class MovieModelForm(ModelForm):

    class Meta:
        model = Movie       # z kterého modelu bude brát informace
        #fields = ['genre', 'title']  # které položky chceme ve formuláři zobrazit
        #exclude = ['description']    # které položky nechceme zobrazit
        fields = '__all__'

    title = CharField(validators=[capitalized_validator])
    rating = IntegerField(min_value=1, max_value=10)
    released = PastMonthField()

    def clean_title(self):
        initial_data = super().clean()  # původní data ve formuláři od uživatele
        initial = initial_data['title']  # původní title od uživatele
        return initial.strip()  # odtraníme prázdné znaky na začátku a konci textu

    def clean_description(self):
        # Force each sentence of the description to be capitalized.
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        return '. '.join(sentence.capitalize() for sentence in sentences)

    def clean(self):
        result = super().clean()
        """if result['genre'].name == 'Commedy' and result['rating'] > 5:
            self.add_error('genre', '')
            self.add_error('rating', '')
            raise ValidationError(
                "Commedies aren't so good to be rated over 5."
            )"""
        return result


class MovieFormView(FormView):
    template_name = 'form.html'
    form_class = MovieModelForm
    success_url = reverse_lazy('movie_create')

    def form_valid(self, form):
        result = super().form_valid(form)
        cleaned_data = form.cleaned_data
        Movie.objects.create(
            title=cleaned_data['title'],

viewer/templates/creator.html
{% extends "base.html" %}

{% block content %}

<div class="creator-details">
    <h1>{{ creator.name}} {{ creator.surname|upper }}</h1>
    <p>Datum narození: {{ creator.birth_date|date:"j. n. Y" }} (age: {{ creator.age }})</p>
    <p>Místo narození: {{ creator.birth_place }}</p>
    {% if creator.death_date %}
    <p>Datum úmrtí: {{ creator.death_date|date:"j. n. Y" }}</p>
    {% endif %}
    <p>Země: {{ creator.country }}</p>
    <p>Pohlaví: {{ creator.sex }}</p>

    <p>
        {% if creator.directed_movies.all.count %}
            Režie:
            {% for movie in creator.directed_movies.all %}
                <a href="{% url 'movie' movie.id %}">{{ movie }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
        {% endif %}
    </p>
    <p>
        {% if creator.acting_in_movies.all.count %}
            Herectví:
            {% for movie in creator.acting_in_movies.all %}
                <a href="{% url 'movie' movie.id %}">{{ movie }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
        {% endif %}
    </p>

    <p>Biografie: {{ creator.biography }}</p>
</div>
{% endblock %}

viewer/templates/creator_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete creator "{{ object }}" from database?
    </p>
    <input type="submit" value="Submit" class="btn btn-danger">
</form>
{% endblock %}

viewer/templates/creators.html
{% extends "base.html" %}

{% block content %}
<h1>List of creators</h1>
<ul>
    {% for creator in creators %}
        <li><a href="{% url 'creator' creator.id %}">{{ creator }}</a>
            {{ creator.print_counts }}
            {% if user.is_authenticated %}
                {% if perms.viewer.change_creator %}
                    <a href="{% url 'creator_update' creator.id %}">✏️</a>
                {% endif %}
                {% if perms.viewer.delete_creator %}
                    <a href="{% url 'creator_delete' creator.id %}">❌</a>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
    {% if perms.viewer.add_creator %}
        <a href="{% url 'creator_create' %}">✖️</a>
    {% endif %}
{% endif %}

{% endblock %}

viewer/templates/form.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

viewer/templates/genre.html
{% extends "base.html" %}

{% block content %}
<h1>Genre: {{ genre }}</h1>
<ul>
    {% for movie in movies %}
        <li><a href="{% url 'movie' movie.id %}">{{ movie }}</a></li>
    {% empty %}
        <p>No movie of this genre in database.</p>
    {% endfor %}
</ul>

<a href="{% url 'genre_update' genre.id %}">Update</a>
<a href="{% url 'genre_delete' genre.id %}">Delete</a>

{% endblock %}

viewer/templates/genre_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete genre "{{ object.name }}" from database?
    </p>
    <input type="submit" value="Submit" class="btn btn-danger">
</form>
{% endblock %}

viewer/templates/genres.html
{% extends "base.html" %}

{% block content %}
<h1>List of genres</h1>
<ul>
    {% for genre in genres %}
        <li><a href="{% url 'genre' genre.id %}">{{ genre }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

viewer/templates/genres2.html
{% extends "base.html" %}

{% block content %}
<h1>List of genres</h1>
<ul>
    {% for genre in object_list %}
        <li>
            {% if genre.movies.all.count %}
                <a href="{% url 'genre' genre.id %}">{{ genre }}</a>
            {% else %}
                {{ genre }}
            {% endif %}
            (movies: {{ genre.movies.all.count }})
            {% if user.is_authenticated %}
                {% if perms.viewer.change_genre %}
                    <a href="{% url 'genre_update' genre.id %}">✏️</a>
                {% endif %}
                {% if perms.viewer.delete_genre %}
                    <a href="{% url 'genre_delete' genre.id %}">❌</a>
                {% endif %}
            {% endif %}
        </li>
    {% empty %}
        <p>List of genres is empty.</p>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
    {% if perms.viewer.add_genre %}
        <a href="{% url 'genre_create' %}">✖️</a>
    {% endif %}
{% endif %}
{% endblock %}

viewer/templates/hello.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            HELLO
        </title>
    </head>
    <body>
        <h1>Welcome to HollyMovies!</h1>
            {% for adjective in adjectives %}
                {% if adjective != 'cruel' %}
                    <p>This is a {{ adjective }} world...</p>
                {% endif %}
            {% endfor %}
    </body>
</html>

viewer/templates/movie_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete movie "{{ object.title }}" from database?
    </p>
    <input type="submit" value="Submit" class="btn btn-danger">
</form>
{% endblock %}

viewer/templates/movie_form.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.title.errors }}
        <label for="{{ form.title.id_for_label }}">Title:</label>
        {{ form.title }}
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                {{ form.genre.errors }}
                <label for="{{ form.genre.id_for_label }}">Genre:</label>
                {{ form.genre }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                {{ form.rating.errors }}
                <label for="{{ form.rating.id_for_label }}">Rating:</label>
                {{ form.rating }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                {{ form.released.errors }}
                <label for="{{ form.released.id_for_label }}">Released:</label>
                {{ form.released }}
            </div>
        </div>
    </div>
    <div class="form-group">
        {{ form.description.errors }}
        <label for="{{ form.description.id_for_label }}">Description:</label>
        {{ form.description }}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block content %}
<h1>List of movies</h1>
<ul>
    {% for movie in movies %}
        <li><a href="{% url 'movie' movie.id %}">{{ movie }} - {{ movie.genre.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

viewer/templates/movies2.html
{% extends "base.html" %}

{% block content %}
<h1>List of movies</h1>
<ul>
    {% for movie in object_list %}
        <li><a href="{% url 'movie' movie.id %}">{{ movie }}</a>:
            {% for genre in movie.genres.all %}
                {{ genre }}{% if not forloop.last %},{% endif %}
            {% empty %}
                Movie has no genre
            {% endfor %}
            ({{ movie.clicked }})
        </li>
    {% endfor %}
</ul>
{% endblock %}

viewer/templates/movies_by_popularity.html
{% extends "base.html" %}

{% block content %}
<h1>List of movies by popularity:</h1>
<ul>
    {% for movie in movies %}
        <li><a href="{% url 'movie' movie.id %}">{{ movie }} - {{ movie.clicked }}</a></li>
    {% endfor %}
</ul>
{% endblock %}