hollymovies/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
import api.views
from accounts.views import SubmittableLoginView, SubmittablePasswordChangeView, SignUpView, ProfilesListView, \
    ProfileDetailView, ProfileUpdateView, ProfileDeleteView
from viewer.views import *


urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello/', hello),
    path('hello2/<s>/', hello2),  # User data: Regular expression, eg. http://127.0.0.1:8000/hello2/cruel/
    path('hello3/', hello3),      # User data: URL encoding, eg. http://127.0.0.1:8000/hello3/?s=cruel
    path('hello4/', hello4),
    path('hello5/<s0>/', hello5),

    path('', home, name='home'),  # home

    #path('genres/', genres, name='genres'),
    path('genres/', GenresView.as_view(), name='genres'),
    #path('genre/create/', GenreFormView.as_view(), name='genre_create'),
    path('genre/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),
    path('genre/<pk>/', genre, name='genre'),

    #path('movies/', movies, name='movies'),
    path('movies/', MoviesView.as_view(), name='movies'),
    #path('movies_by_rating/', movies_by_rating, name='movies_by_rating'),
    path('movies_by_rating/', MoviesByRatingView.as_view(), name='movies_by_rating'),
    path('movies_by_popularity/', MoviesByPopularityView.as_view(), name='movies_by_populartiy'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/<pk>/', movie, name='movie'),
    path('creators/', CreatorsView.as_view(), name='creators'),
    path('creator/create/', CreatorCreateView.as_view(), name='creator_create'),
    path('creator/update/<pk>/', CreatorUpdateView.as_view(), name='creator_update'),
    path('creator/delete/<pk>/', CreatorDeleteView.as_view(), name='creator_delete'),
    path('creator/<pk>/', CreatorView.as_view(), name='creator'),

    # authentication
    #path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/login/', SubmittableLoginView.as_view(), name='login'),  # vlastní view pro login
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/password_change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('accounts/', include('django.contrib.auth.urls')),  # defaultní view pro přihlašování/odhlašování/změnu hesla...

    path('accounts/profiles/', ProfilesListView.as_view(), name='profiles'),
    path('accounts/profile/<pk>/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/update/<pk>/', ProfileUpdateView.as_view(), name='profile_update'),
    path('accounts/profile/delete/<pk>/', ProfileDeleteView.as_view(), name='profile_delete'),

    # API
    path('api-auth', include('rest_framework.urls'), namespace='rest_framework'),
    path('api/movies/', api.views.MovieList.as_view()),
    path('api/movie/<pk>/', api.views.MovieDetail.as_view()),
]

viewer/models.py
from datetime import date

from django.db.models import Model, CharField, ForeignKey, DO_NOTHING, IntegerField, DateField, TextField, \
    DateTimeField, ManyToManyField, TextChoices


class Genre(Model):
    name = CharField(max_length=20)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Country(Model):
    name = CharField(max_length=64)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class Sex(TextChoices):
    MAN = 'man'
    WOMAN = 'woman'
    NON_BINARY = 'non-binary'


class Creator(Model):
    name = CharField(max_length=32)
    surname = CharField(max_length=32, blank=True)
    birth_date = DateField(null=True, blank=True)
    death_date = DateField(null=True, blank=True)
    birth_place = CharField(max_length=64, null=True, blank=True)
    country = ForeignKey(Country, null=True, blank=True, on_delete=DO_NOTHING)
    sex = CharField(max_length=10, choices=Sex.choices, null=True, blank=True)
    biography = TextField(null=True, blank=True)

    class Meta:
        ordering = ['surname', 'name', 'birth_date']

    def __str__(self):
        return f"{self.name} {self.surname} ({self.birth_date.year})"

    def print_counts(self):
        result = ""
        if self.directed_movies.count() or self.acting_in_movies.count():
            result = "("
            if self.directed_movies.count():
                result += f"director: {self.directed_movies.count()}"
                if self.acting_in_movies.count():
                    result += ", "
            if self.acting_in_movies.count():
                result += f"actor: {self.acting_in_movies.count()}"
            result += ")"
        return result

    def age(self):
        start_date = self.birth_date
        end_date = date.today()
        if self.death_date:
            end_date = self.death_date
        age = end_date.year - start_date.year
        if end_date.month < start_date.month:
            age -= 1
        if end_date.month == start_date.month and end_date.day < start_date.day:
            age -= 1
        return age


class Movie(Model):
    title = CharField(max_length=64)
    title_cz = CharField(max_length=64, blank=True)
    # genre = ForeignKey(Genre, on_delete=DO_NOTHING)
    genres = ManyToManyField(Genre, blank=True, related_name='movies')
    countries = ManyToManyField(Country, blank=True, related_name='movies')
    directors = ManyToManyField(Creator, blank=True, related_name='directed_movies')
    actors = ManyToManyField(Creator, blank=True, related_name='acting_in_movies')
    rating = IntegerField()
    released = DateField()
    length = IntegerField(null=True, blank=True)
    description = TextField(null=True)
    clicked = IntegerField(default=0)
    created = DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title', 'released']

    def __str__(self):
        return f'{self.title} ({self.released.year})'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% else %}lang="en"{% endif %}>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% if title %}
            {{ title }}
        {% else %}
            HollyMovies
        {% endif %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</head>

<body>

{% include "nav.html" %}

<div class="container">
    <div class="jumbotron">
        {% block content %}{% endblock %}
    </div>
</div>

{% include "footer.html" %}

</body>

</html>

templates/footer.html
<footer>
    Holubex
</footer>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="{% url 'home' %}">HollyMovies</a>
        <button
                class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'home' %}">
                    Home
                </a>
                <a class="nav-item nav-link active" href="{% url 'movies' %}">Movies</a>
                <a class="nav-item nav-link active" href="{% url 'movies_by_rating' %}">Movies by rating</a>
                <a class="nav-item nav-link active" href="{% url 'genres' %}">Genres</a>
                <a class="nav-item nav-link active" href="{% url 'creators' %}">Creators</a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link active" href="{% url 'profiles' %}">Profiles</a>
                    {% if perms.viewer.add_movie %}
                        <a class="nav-item nav-link active" href="{% url 'movie_create' %}">Add movie</a>
                    {% endif %}
                    {% if perms.viewer.add_genre %}
                        <a class="nav-item nav-link active" href="{% url 'genre_create' %}">Add genre</a>
                    {% endif %}
                    {% if perms.viewer.add_creator %}
                        <a class="nav-item nav-link active" href="{% url 'creator_create' %}">Add creator</a>
                    {% endif %}
                {% endif %}
            </div>

            <div class="navbar-nav ml-auto">
                <div class="nav-item dropdown">
                    {% if user.is_authenticated %}
                        <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                            {% if user.first_name %}Hello, {{ user.first_name }}!
                            {% else %}Hello, {{ user.username }}!{% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item text-right" href="{% url 'logout' %}">Logout</a>
                            <a class="dropdown-item text-right" href="{% url 'password_change' %}">Change password</a>
                        </div>
                    {% else %}
                        <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                            You are not logged in.
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item text-right" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item text-right" href="{% url 'signup' %}">Sign-up</a>
                        </div>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</nav>